# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='client',
            field=models.GenericIPAddressField(help_text=b'IP of the commenter'),
        ),
    ]
